# Chapter 2: (There's no Chapter 1...)

In [18]:
# Preface: Install necessary packages:
import numpy as np

## Section 1: A Single Neuron
In this problem we're basically building out a single neuron to get an intuition about how it works. I was debating doing this part out, but I think it can't hurt and foundations are super important IMO.

Fundamentally, the output of any singular neuron is determined by three things: inputs, weights, and bias. The inputs are naturally kept the same, but weights and biases change as the model trains. Every neuron will have n weights corresponding to the n incoming connections coming from the previous layer. These are then summed in the neuron and a bias is then added to make the neuron generalize better. Then there's something about activation functions, but we're not there yet.

Side note: it's fascinating to see how this connects to the human brain.

In [19]:
# Given a singular neuron with X incoming connections...

inputs = [2, 4, 6] # of length X, 1 for every incoming connection
weights = [.8, .75, .3] # also of length X, 1 for every incoming connection
bias = 1.5 # just a singular value, as there's only 1 per neuron

# the below is the neuron output, which takes the form: Output = (Inputs * Weights) + Bias
output = ((inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2]) + bias)

print(output)

7.8999999999999995


This may not look like much... because it really isn't. But it is a nice intuition that will let us build up on the notion of neural networks (not too far!) down the line.

## Section 2: A Layer of Neurons
> The book says: "neural networks typically have layers that consist of more than one neuron." Fascinating.

Each neuron in a layer gets the same input, BUT each neuron consists of its own of weights and bias, meaning each will (barring the same weights) produce different outputs.

So, let's build a true "layer" of neurons. 

In [20]:
# Given a dense layer with 3 neurons each with in-degree 4 (meaning four incoming connections from the previous layer)...

inputs = [1, 3, 4, 2] # of length 4, given the 4 inputs

# weights of length 4, because 3 neurons each with 4 in-degree.
weights = [[.1, .3, .2, .75], [.9, .1, 1, -.3], [-.4, .6, .2, 1]]

# 3 singular values; 1 per neuron
biases = [2, 3, .5]

# the below are the outputs of the layer. we basically just do matrix multiplication and we're definitely going to be doing this using numpy in the near future. For anyone interested: this has a variety of advantages, it's extremely efficient. Look into it!
outputs = [
    inputs[0]*weights[0][0] + inputs[1]*weights[0][1] + inputs[2]*weights[0][2] + inputs[3]*weights[0][3] + biases[0],
    inputs[0]*weights[1][0] + inputs[1]*weights[1][1] + inputs[2]*weights[1][2] + inputs[3]*weights[1][3] + biases[1],
    inputs[0]*weights[2][0] + inputs[1]*weights[2][1] + inputs[2]*weights[2][2] + inputs[3]*weights[2][3] + biases[2],
]

print(f"Statically calculated version: {outputs}")

# As I said, the way above doesn't really scale, but we can make it a little bit better with the use of loops to dynamically do this.
outputs = []
for neuronWeights, neuronBias in zip(weights, biases):
    neuronOutput = 0
    for nInput, weight in zip(inputs, neuronWeights):
        neuronOutput += nInput * weight
    neuronOutput += neuronBias
    outputs.append(neuronOutput)
        
print(f"Dynamically calculated version: {outputs}")

Statically calculated version: [5.3, 7.6000000000000005, 4.7]
Dynamically calculated version: [5.3, 7.6000000000000005, 4.7]


The above is technically called a "fully connected" neural network - where every neuron in the current layer has a connection to each neuron in the previous layer. 

The number of neurons you use in each layer is totally up to you, and we'll find out throughout the course of the book what can influence your choices there. 

## Section 3: Tensors, Arrays, Vectors

I'll assume everyone's familiar with basic python and the differences between and names for the following: a = [1,2] vs b = [[1],[2]] vs c = [[1,2],[3,4,5]]. 

In this above example, a and b can be arrays, while c cannot because it is not "homologous." That is because row 1 is of length 2 whereas row 2 is of length 3, meaning it doesn't follow the form of an array.

A matrix is a rectangular array with columns and rows. It can be 2D in the simple case of an (n x m) matrix, lets call it A, where each entry A[i][j], letting i be the row and j be the column, is a single integer. However, we can scale up this matrix in dimensionality by adding more lists in each list. Linear algebra was my favourite class so far, and I geek out about that kind of stuff.

I'll show a 2D vs 3D matrix below:  

In [21]:
# matrixA: a 2D matrix of shape (3, 4)
matrixA = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

# Let's print the entry at row 0 and column 1. 
print(f"The entry at row 0 and column 1 is: {matrixA[0][1]}")

# matrixB: a 3D matrix of shape (3, 2, 4)
matrixB = [
    [[1,2,3,4],
     [5,6,7,8]],
    [[9,10,11,12],
     [13,14,15,16]],
    [[17,18,19,20],
     [21,22,23,24]]
]

# Now we can get the entry at the entry i = 0, j = 1, k = 2. I wish I could word that better.
print(f"The entry at i = 0, j = 1, k = 2 is: {matrixB[0][1][2]}")

The entry at row 0 and column 1 is: 2
The entry at i = 0, j = 1, k = 2 is: 7


Now, about tensors:
> A tensor is an object that can be represented as an array.

Not all tensors are arrays, every array can be viewed as a tensor. For the purposes of this work, we're told to just view them as one and the same.

Lastly, about vectors:
> Vectors are just 1D lists in python.

## Section 4: Dot Product and Vector Addition

Both dot products and cross products are ways to do vector multiplication. The difference is, the dot product results in a scalar, whereas the cross product results in a vector.

Dot products are technically just element-wise multiplication, where both vectors must be of the same size. I'll show an example below:

In [22]:
# Given vectors X and Y in a 2D space
x = [1, 2]
y = [3, 4]

# The dot product is therefore:
dP = x[0]*y[0] + x[1]*y[1]

## Section 5: A Single Neuron with Numpy

This section is a re-creation of section 1, but it's done with numpy instead of manually coding it out. That means we're creating a single neuron to operate on.

Let's see how much more efficient we can make it. 

In [23]:
inputs = [1.0, 2.1, 3.2, 4.3]
weights = [.3, .4, .7, .2]
bias = 2.0

outputs = np.dot(inputs, weights) + bias

print(f"The neuron output is: {outputs}")

The neuron output is: 6.24


## Section 6: A Layer of Neurons with Numpy

This section is a re-creation of section 2, but it instead uses numpy to make the multiplication operation more efficient.

We'll create a dense layer of 3 neurons, each with 4 in-degree. 

In [24]:
inputs = [1.0, 2.1, 3.2, 4.3]
weights = [[0.3, 0.2, 0.4, 0.1],
           [0.9, 0.1, 0.8, 0.6],
           [.7, 0.2, 0.1, 0.2]]
biases = [0.3, 1.2, 2.0]

outputs = np.dot(weights, inputs) + biases

print(outputs)

[2.73 7.45 4.3 ]


## Section 7: A Batch of Data

Neural networks typically receive training data in batches! So, what we've been providing so far has been one sample. The reason why we typically train in batches is since a batch is a collection of multiple samples, which has the effect of making the model more generalizable across the whole dataset, versus exactly tuned to the noise of individual samples.

## Section 8: Matrix Products & Transpositions

A matrix product takes two matrices and does dot products on all the possible combinations of rows in one matrix and columns in the other. For this to work, the dimensionality of the two matrices needs to be (n x m) and (m x p) where the width of the first matrix needs to coincide with the height of the second matrix.

We can also carry out matrix products on vectors, called the row and column vector, that we treat as a (1 x m) or (m x 1) matrix, respectively. This then produces a matrix of size (1 x 1).

By the relation of dot products and matrices, we know that:
> a * b = ab.T # Where the ".T" means transpose.

A transposition means the rows and columns are flipped. I'll provide a little example below

In [25]:
matrixA = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]

matrixATranspose = [
    [1, 5],
    [2, 6],
    [3, 7],
    [4, 8]
]

Now, with this knowledge, we can use Numpy to actually do this vector multiplication.

Side note: Numpy does not have separate methods for matrix or dot product, they're just both referred to as "np.dot(a, b)."

In [26]:
x = np.array([1,2,3])
y = np.array([4,5,6]).T

# Now our multiplication follows the form Output = ab.T
mMult = np.dot(x, y)
print(mMult)

32


## Section 9: A Layer of Neurons & Batch of Data with Numpy

This is effectively the culmination of this entire chapter, where we'll create a layer of neurons that we'll feel a batch of data -- and it'll be easy, thanks to Numpy.

In [27]:
inputs = [[1.0, 2.0, 3.0, 4.0],
          [5.0 , 6.0, 7.0, 8.0],
          [9.0, 10.0, 11.0, 12.0]]
weights = [[.3, .4, .8, .7],
           [.4, .5, .9, .8],
           [.5, .6, .0, .9]]
biases = [6.2, 7.3, 0.5]

layerOutputs = np.dot(inputs, np.array(weights).T) + biases

print(layerOutputs)

[[12.5 14.6  5.8]
 [21.3 25.  13.8]
 [30.1 35.4 21.8]]


The above may seem meaningless, and it kind of is? But it's the first full set of predictions that we've made given an input. That is cool, and it'll be even cooler once we actually use it to predict something meaningful! 

### Anyways, that's it for this chapter! Thanks for following along with my annotations of *Neural Networks from Scratch* by Kinsley and Kukieła!